apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: curator-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CuratorConfig is the Schema for the curatorconfigs API
      displayName: Curator Config
      kind: CuratorConfig
      name: curatorconfigs.curator.operatefirst.io
      version: v1alpha1
    - description: FetchData is the Schema for the fetchdata API
      displayName: Fetch Data
      kind: FetchData
      name: fetchdata.curator.operatefirst.io
      version: v1alpha1
    - description: Report is the Schema for the reports API
      displayName: Report
      kind: Report
      name: reports.curator.operatefirst.io
      version: v1alpha1
  description: stub
  displayName: curator-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - metering
  - metrics
  - reporting
  links:
  - name: Documentation
    url: https://curator-doc.readthedocs.io/en/latest/
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://github.com/operate-first/curator
  version: 0.0.0
