## Append samples you want in your CSV to this file as resources ##
resources:
- curator_v1alpha1_report.yaml
- curator_v1alpha1_curatorconfig.yaml
- curator_v1alpha1_fetchdata.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
